# Generated by Django 6.0.2 on 2026-02-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "grp_id",
                    models.IntegerField(
                        help_text="Arena's card group ID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("mana_cost", models.CharField(blank=True, max_length=100, null=True)),
                ("cmc", models.FloatField(blank=True, help_text="Converted mana cost", null=True)),
                ("type_line", models.CharField(blank=True, max_length=255, null=True)),
                ("colors", models.JSONField(blank=True, default=list)),
                ("color_identity", models.JSONField(blank=True, default=list)),
                ("set_code", models.CharField(blank=True, max_length=10, null=True)),
                ("rarity", models.CharField(blank=True, max_length=20, null=True)),
                ("oracle_text", models.TextField(blank=True, null=True)),
                ("power", models.CharField(blank=True, max_length=10, null=True)),
                ("toughness", models.CharField(blank=True, max_length=10, null=True)),
                ("scryfall_id", models.CharField(blank=True, max_length=50, null=True)),
                ("image_uri", models.URLField(blank=True, max_length=500, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Cards",
                "db_table": "cards",
            },
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "deck_id",
                    models.CharField(help_text="UUID from MTG Arena", max_length=100, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("format", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "decks",
            },
        ),
        migrations.CreateModel(
            name="ImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("log_file", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_modified", models.DateTimeField(blank=True, null=True)),
                ("matches_imported", models.IntegerField(default=0)),
                ("matches_skipped", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "import_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match_id",
                    models.CharField(help_text="UUID from MTG Arena", max_length=100, unique=True),
                ),
                (
                    "game_number",
                    models.IntegerField(default=1, help_text="Game number within match (Bo3)"),
                ),
                ("player_seat_id", models.IntegerField(blank=True, null=True)),
                ("player_name", models.CharField(blank=True, max_length=255, null=True)),
                ("player_user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("opponent_seat_id", models.IntegerField(blank=True, null=True)),
                ("opponent_name", models.CharField(blank=True, max_length=255, null=True)),
                ("opponent_user_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        help_text="Ladder, Traditional_Standard, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("format", models.CharField(blank=True, max_length=50, null=True)),
                ("match_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("win", "Win"),
                            ("loss", "Loss"),
                            ("draw", "Draw"),
                            ("incomplete", "Incomplete"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("winning_team_id", models.IntegerField(blank=True, null=True)),
                ("winning_reason", models.CharField(blank=True, max_length=100, null=True)),
                ("player_final_life", models.IntegerField(blank=True, null=True)),
                ("opponent_final_life", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("total_turns", models.IntegerField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="stats.deck",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="LifeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("game_state_id", models.IntegerField(blank=True, null=True)),
                ("turn_number", models.IntegerField(blank=True, null=True)),
                ("seat_id", models.IntegerField()),
                ("life_total", models.IntegerField()),
                ("change_amount", models.IntegerField(blank=True, null=True)),
                ("source_instance_id", models.IntegerField(blank=True, null=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_changes",
                        to="stats.match",
                    ),
                ),
            ],
            options={
                "db_table": "life_changes",
                "ordering": ["game_state_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="GameAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("game_state_id", models.IntegerField(blank=True, null=True)),
                ("turn_number", models.IntegerField(blank=True, null=True)),
                ("phase", models.CharField(blank=True, max_length=50, null=True)),
                ("step", models.CharField(blank=True, max_length=50, null=True)),
                ("active_player_seat", models.IntegerField(blank=True, null=True)),
                (
                    "seat_id",
                    models.IntegerField(
                        blank=True, help_text="Who performed the action", null=True
                    ),
                ),
                ("action_type", models.CharField(max_length=50)),
                ("instance_id", models.IntegerField(blank=True, null=True)),
                ("ability_grp_id", models.IntegerField(blank=True, null=True)),
                ("mana_cost", models.JSONField(blank=True, null=True)),
                ("target_ids", models.JSONField(blank=True, null=True)),
                ("timestamp_ms", models.BigIntegerField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        db_column="card_grp_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.card",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="stats.match",
                    ),
                ),
            ],
            options={
                "db_table": "game_actions",
                "ordering": ["game_state_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ZoneTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("game_state_id", models.IntegerField(blank=True, null=True)),
                ("turn_number", models.IntegerField(blank=True, null=True)),
                ("instance_id", models.IntegerField(blank=True, null=True)),
                ("from_zone", models.CharField(blank=True, max_length=50, null=True)),
                ("to_zone", models.CharField(blank=True, max_length=50, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        blank=True,
                        db_column="card_grp_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stats.card",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_transfers",
                        to="stats.match",
                    ),
                ),
            ],
            options={
                "db_table": "zone_transfers",
                "ordering": ["game_state_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeckCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("is_sideboard", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        db_column="card_grp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stats.card",
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck_cards",
                        to="stats.deck",
                    ),
                ),
            ],
            options={
                "db_table": "deck_cards",
                "unique_together": {("deck", "card", "is_sideboard")},
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["match_id"], name="matches_match_i_feaf87_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["start_time"], name="matches_start_t_f662c7_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["result"], name="matches_result_e961d1_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["opponent_name"], name="matches_opponen_29b6c0_idx"),
        ),
        migrations.AddIndex(
            model_name="gameaction",
            index=models.Index(
                fields=["match", "turn_number"], name="game_action_match_i_e7fd96_idx"
            ),
        ),
    ]
