# Generated by Django 6.0.2 on 2026-02-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnknownCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw card data from log file if available (for debugging)",
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False, help_text="Whether card has been manually resolved"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        db_column="grp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unknown_occurrences",
                        to="stats.card",
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unknown_cards",
                        to="stats.deck",
                    ),
                ),
                (
                    "import_session",
                    models.ForeignKey(
                        help_text="Import session where this unknown card was discovered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unknown_cards",
                        to="stats.importsession",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unknown_cards",
                        to="stats.match",
                    ),
                ),
            ],
            options={
                "db_table": "unknown_cards",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_resolved"], name="unknown_car_is_reso_33a012_idx"),
                    models.Index(
                        fields=["card", "is_resolved"], name="unknown_car_grp_id_d3f73d_idx"
                    ),
                ],
            },
        ),
    ]
