# Generated by Django 6.0.2 on 2026-02-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_unknowncard"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_token",
            field=models.BooleanField(
                default=False, help_text="True for tokens and emblems created by card abilities"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="object_type",
            field=models.CharField(
                blank=True,
                help_text="Arena game object type (e.g. GameObjectType_Token)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="source_grp_id",
            field=models.IntegerField(
                blank=True, help_text="grpId of the card that created this token/emblem", null=True
            ),
        ),
    ]
