# Generated by Django 6.0.2 on 2026-03-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("scryfall_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("type_line", models.CharField(blank=True, max_length=255)),
                ("oracle_text", models.TextField(blank=True)),
                ("mana_cost", models.CharField(blank=True, max_length=100)),
                ("colors", models.JSONField(default=list)),
                ("set_code", models.CharField(blank=True, max_length=10)),
                ("rarity", models.CharField(blank=True, max_length=20)),
                ("image_uri", models.URLField(blank=True, max_length=500)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "paper_cards",
                "ordering": ["name"],
            },
        ),
    ]
