# Generated by Django 6.0.3 on 2026-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="papercard",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
